const labels: Readonly<Record<string, string>> = Object.freeze({
  SNAPSHOT: "快照固化",
  CANDIDATE_PREVIEW: "候选知识生成",
  POLICY_COMMIT: "策略确认",
  KNOWLEDGE_PUBLICATION: "知识发布",
  EPISODE_BUILD: "对话片段构建",
  EVIDENCE: "证据校验",

  SNAPSHOT_IMMUTABLE: "快照已固化，不会被后续会话变化覆盖",
  SNAPSHOT_NOT_CREATED: "尚未创建提取快照",
  SNAPSHOT_REQUIRED: "需要先创建提取快照",
  CANDIDATE_PREVIEW_NOT_ENQUEUED: "候选知识生成任务尚未入队",
  CANDIDATE_PREVIEW_QUEUED: "候选知识生成任务已排队",
  CANDIDATE_PREVIEW_RUNNING: "正在生成候选知识",
  CANDIDATE_PREVIEW_RETRY_WAIT: "候选知识生成正在等待重试",
  CANDIDATE_PREVIEW_CANCEL_REQUESTED: "正在取消候选知识生成任务",
  CANDIDATE_PREVIEW_CANCELLED: "候选知识生成任务已取消",
  CANDIDATE_PREVIEW_FAILED: "候选知识生成失败",
  CANDIDATE_PREVIEW_RESULT_MISSING: "任务已完成，但候选知识结果缺失",
  CANDIDATE_PREVIEW_PENDING: "候选知识尚未生成",
  CANDIDATE_PREVIEW_READY: "候选知识已生成，可检查后提交",
  KNOWLEDGE_PREVIEW_INCOMPLETE: "候选知识生成结果不完整",
  KNOWLEDGE_PREVIEW_FAILED: "知识编译过程失败",
  KNOWLEDGE_WORKER_NOT_CONFIGURED: "知识编译器尚未配置",
  EXTRACTION_SNAPSHOT_NOT_FOUND: "提取快照不存在",
  JOB_LEASE_EXPIRED: "后台任务执行租约已过期",
  JOB_MAX_ATTEMPTS_EXHAUSTED: "后台任务已达到最大重试次数",
  JOB_NON_RETRYABLE_FAILURE: "后台任务发生不可重试失败",
  JOB_HANDLER_FAILED: "后台任务处理器执行失败",
  JOB_HANDLER_NOT_FOUND: "没有找到对应的后台任务处理器",
  JOB_CANCELLED: "后台任务已取消",
  JOB_CANCELLATION_REQUESTED: "后台任务正在取消",
  EXPLICIT_COMMIT_REQUIRED: "需要明确确认后才能发布",
  POLICY_COMMITTED: "知识策略已确认",
  PUBLICATION_PENDING: "等待知识发布",
  MARKDOWN_REGISTRY_INDEX_AND_PROVENANCE_COMMITTED: "正文、索引与来源链均已写入",
  STAGE_COMPLETE: "阶段已完成",
  EVIDENCE_PARTIAL: "证据不完整",
  ACTION_READY: "当前可以执行",
  PREVIEW_NOT_READY: "候选知识尚未准备好",
  POLICY_ALREADY_COMMITTED: "策略已经提交",
  CAPABILITY_NOT_VERIFIED: "能力尚未验证",
  CAPTURE_NOT_CURRENT: "会话尚未采集至最新",
  PARTIAL_SNAPSHOT: "部分快照",
  COMPLETE_SNAPSHOT: "完整快照",
  TOOL_STREAM_DELTA: "工具流式增量事件",
  unsupported_transcript_record: "暂不支持的会话记录",

  FACT: "事实",
  REQUIREMENT: "需求",
  DESIGN: "设计方案",
  DECISION: "技术决策",
  IMPLEMENTATION: "实现记录",
  EXPERIENCE: "使用经验",
  RULE: "规则",
  PREFERENCE: "偏好",
  OPEN_QUESTION: "待解决问题",
  TASK: "任务",
  SYMBOL: "代码符号",
  MODULE: "模块",
  PROJECT: "项目",
  GLOBAL: "全局",
  PUBLISH: "发布",
  KEEP_PROPOSED: "保留为候选",
  REQUIRE_CONFIRMATION: "需要人工确认",
  REJECT: "拒绝",
  SUPPORTS: "支持",
  CONTRADICTS: "存在矛盾",
  INCONCLUSIVE: "证据不足",
  PROPOSED: "待确认",
  ACCEPTED: "已接受",
  IMPLEMENTED: "已实现",
  VERIFIED: "已验证",
  STALE: "已过期",
  SUPERSEDED: "已替代",
  REJECTED: "已拒绝",
});

const details: Readonly<Record<string, string>> = Object.freeze({
  KNOWLEDGE_PREVIEW_INCOMPLETE: "后台闭环没有产出可提交的候选策略结果。系统会按重试策略重新执行；若达到最大次数仍未成功，任务将转为失败。",
  KNOWLEDGE_PREVIEW_FAILED: "知识编译流水线返回失败。请结合后台任务中的尝试记录判断具体失败阶段。",
  CANDIDATE_PREVIEW_RESULT_MISSING: "后台任务报告成功，但持久化存储中没有对应候选预览，需要检查任务完成与结果写入的原子性。",
  JOB_LEASE_EXPIRED: "任务开始执行后，工作进程未能在租约期限内持续上报心跳。常见原因是服务重启、进程退出或执行被中断；系统会在重试额度内重新执行。",
  JOB_MAX_ATTEMPTS_EXHAUSTED: "任务已经用完自动重试额度，需要先查看各次尝试的失败记录，再决定是否手动重试。",
  JOB_NON_RETRYABLE_FAILURE: "后台判断该错误继续重试也不会自行恢复，需要修复配置或输入后重新发起。",
  JOB_HANDLER_FAILED: "任务处理器抛出了未归类异常，请在后台任务页查看对应尝试记录。",
  JOB_HANDLER_NOT_FOUND: "当前运行版本没有注册该任务类型的处理器，需检查组件部署与版本匹配。",
});

export function p2EnumLabel(value: string): string {
  return labels[value] ?? value;
}

export function p2ReasonDetail(value: string): string | undefined {
  return details[value];
}
