const labels: Readonly<Record<string, string>> = Object.freeze({
  SNAPSHOT: "快照固化",
  CANDIDATE_PREVIEW: "候选知识生成",
  POLICY_COMMIT: "策略确认",
  KNOWLEDGE_PUBLICATION: "知识发布",
  EPISODE_BUILD: "对话片段构建",
  EVIDENCE: "证据校验",
  KNOWLEDGE_COMPILE: "对话知识编译",
  KNOWLEDGE_REVALIDATE: "代码知识重新验证",
  KNOWLEDGE_REPAIR_DRAFT: "知识修复草稿",
  CODEGRAPH_INITIALIZE: "CodeGraph 初始化",
  LEGACY_KNOWLEDGE_MIGRATION: "历史知识迁移",

  SNAPSHOT_IMMUTABLE: "快照已固化，不会被后续会话变化覆盖",
  SNAPSHOT_NOT_CREATED: "尚未创建提取快照",
  SNAPSHOT_REQUIRED: "需要先创建提取快照",
  CANDIDATE_PREVIEW_NOT_ENQUEUED: "候选知识生成任务尚未入队",
  CANDIDATE_PREVIEW_QUEUED: "候选知识生成任务已排队",
  CANDIDATE_PREVIEW_RUNNING: "正在生成候选知识",
  CANDIDATE_PREVIEW_RETRY_WAIT: "候选知识生成正在等待重试",
  CANDIDATE_PREVIEW_CANCEL_REQUESTED: "正在取消候选知识生成任务",
  CANDIDATE_PREVIEW_CANCELLED: "候选知识生成任务已取消",
  CANDIDATE_PREVIEW_FAILED: "候选知识生成失败",
  CANDIDATE_PREVIEW_RESULT_MISSING: "任务已完成，但候选知识结果缺失",
  CANDIDATE_PREVIEW_PENDING: "候选知识尚未生成",
  CANDIDATE_PREVIEW_READY: "候选知识已生成，可检查后提交",
  KNOWLEDGE_PREVIEW_INCOMPLETE: "候选知识生成结果不完整",
  KNOWLEDGE_PREVIEW_FAILED: "知识编译过程失败",
  KNOWLEDGE_WORKER_NOT_CONFIGURED: "知识编译器尚未配置",
  EXTRACTION_SNAPSHOT_NOT_FOUND: "提取快照不存在",
  JOB_LEASE_EXPIRED: "后台任务执行租约已过期",
  JOB_MAX_ATTEMPTS_EXHAUSTED: "后台任务已达到最大重试次数",
  JOB_NON_RETRYABLE_FAILURE: "后台任务发生不可重试失败",
  JOB_HANDLER_FAILED: "后台任务处理器执行失败",
  JOB_HANDLER_NOT_FOUND: "没有找到对应的后台任务处理器",
  JOB_CANCELLED: "后台任务已取消",
  JOB_QUEUED: "后台任务已排队",
  JOB_RUNNING: "后台任务运行中",
  JOB_RETRY_WAIT: "后台任务等待重试",
  JOB_SUCCEEDED: "后台任务已成功完成",
  JOB_FAILED: "后台任务执行失败",
  JOB_CANCELLATION_REQUESTED: "后台任务正在取消",
  EXPLICIT_COMMIT_REQUIRED: "需要明确确认后才能发布",
  POLICY_COMMITTED: "知识策略已确认",
  PUBLICATION_PENDING: "等待知识发布",
  MARKDOWN_REGISTRY_INDEX_AND_PROVENANCE_COMMITTED: "正文、索引与来源链均已写入",
  STAGE_COMPLETE: "阶段已完成",
  EVIDENCE_PARTIAL: "证据不完整",
  ACTION_READY: "当前可以执行",
  PREVIEW_NOT_READY: "候选知识尚未准备好",
  POLICY_ALREADY_COMMITTED: "策略已经提交",
  CAPABILITY_NOT_VERIFIED: "能力尚未验证",
  CAPTURE_NOT_CURRENT: "会话尚未采集至最新",
  PARTIAL_SNAPSHOT: "部分快照",
  COMPLETE_SNAPSHOT: "完整快照",
  TOOL_STREAM_DELTA: "工具流式增量事件",
  unsupported_transcript_record: "暂不支持的会话记录",

  FACT: "事实",
  REQUIREMENT: "需求",
  DESIGN: "设计方案",
  DECISION: "技术决策",
  IMPLEMENTATION: "实现记录",
  EXPERIENCE: "使用经验",
  RULE: "规则",
  PREFERENCE: "偏好",
  OPEN_QUESTION: "待解决问题",
  TASK: "任务",
  SYMBOL: "代码符号",
  MODULE: "模块",
  PROJECT: "项目",
  GLOBAL: "全局",
  PUBLISH: "发布",
  KEEP_PROPOSED: "保留为候选",
  REQUIRE_CONFIRMATION: "需要人工确认",
  REJECT: "拒绝",
  USER_ACCEPTED: "用户已明确接受",
  USER_REJECTED: "用户已明确拒绝",
  SYMBOL_EXISTS: "代码符号存在",
  CALL_PATH_EXISTS: "调用路径存在",
  IMPACT_CONTAINS: "影响范围包含目标符号",
  FILE_CONTAINS: "文件包含目标内容",
  DEPENDENCY_PRESENT: "依赖存在",
  CONFIG_EQUALS: "配置值相等",
  COMMAND_SUCCEEDED: "历史命令执行成功",
  TEST_PASSED: "历史测试通过",
  CROSS_PROJECT_VERIFIED: "跨项目验证成立",
  CORRECTION: "用户纠正",
  DECIDED: "已完成演进决策",
  STORE: "新增知识",
  SUPPLEMENT: "补充现有知识",
  SUPERSEDE: "替代旧知识",
  CONTRADICT: "与现有知识冲突",
  SCOPE_SPLIT: "按适用范围拆分",
  SKIP: "跳过重复内容",
  MULTIPLE_PLAUSIBLE_TARGETS: "存在多个可能目标",
  SUPPORTS: "支持",
  CONTRADICTS: "存在矛盾",
  INCONCLUSIVE: "证据不足",
  PROPOSED: "待确认",
  ACCEPTED: "已接受",
  IMPLEMENTED: "已实现",
  VERIFIED: "已验证",
  STALE: "已过期",
  SUPERSEDED: "已替代",
  REJECTED: "已拒绝",
  FRESH: "数据新鲜",
  REVALIDATE: "等待重新验证",
  CONFLICT: "与当前代码冲突",
  UNKNOWN: "保鲜状态未知",
  NOT_PROJECTED: "尚未建立保鲜投影",
  NOT_REQUIRED: "无需代码保鲜",
  PATH: "代码路径",
  CONFIG: "配置项",
  DEPENDENCY: "依赖",
  FRESHNESS_NOT_PROJECTED: "缺少当前版本的保鲜投影",
  FRESHNESS_NOT_REQUIRED: "该知识不依赖代码事实",
  FRESHNESS_REVALIDATE: "代码变化后尚未完成重新验证",
  FRESHNESS_CONFLICT: "重新验证发现知识与代码冲突",
  FRESHNESS_UNKNOWN: "无法确认知识是否仍与代码一致",
  CODEGRAPH_SYMBOL_FOUND: "CodeGraph 已找到目标符号",
  CODEGRAPH_SYMBOL_NOT_FOUND: "CodeGraph 未找到目标符号",
  CODEGRAPH_CALL_PATH_FOUND: "CodeGraph 已找到调用路径",
  CODEGRAPH_CALL_PATH_NOT_FOUND: "CodeGraph 未找到调用路径",
  CODEGRAPH_CALL_PATH_BOUNDED: "调用路径搜索已达到安全边界",
  CODEGRAPH_IMPACT_TARGET_FOUND: "CodeGraph 影响范围包含目标符号",
  CODEGRAPH_IMPACT_TARGET_NOT_FOUND: "CodeGraph 影响范围不包含目标符号",
  CODEGRAPH_NOT_INITIALIZED: "当前项目尚未初始化 CodeGraph",
  CODEGRAPH_INDEX_STALE: "CodeGraph 索引不是当前代码版本",
  CODEGRAPH_UNAVAILABLE: "CodeGraph 当前不可用",
  FILE_LITERAL_FOUND: "文件中已找到目标内容",
  FILE_LITERAL_NOT_FOUND: "文件中未找到目标内容",
  DEPENDENCY_FOUND: "已找到目标依赖",
  DEPENDENCY_NOT_FOUND: "未找到目标依赖",
  DEPENDENCY_VERSION_MATCHED: "依赖版本符合约束",
  DEPENDENCY_VERSION_MISMATCH: "依赖版本不符合约束",
  DEPENDENCY_VERSION_UNRESOLVED: "无法可靠判断依赖版本",
  CONFIG_VALUE_MATCHED: "配置值符合预期",
  CONFIG_VALUE_MISMATCH: "配置值与预期不符",
  SNAPSHOT_COMMAND_EXIT_MATCHED: "快照中的命令退出码符合预期",
  SNAPSHOT_COMMAND_EXIT_MISMATCH: "快照中的命令执行结果不符",
  SNAPSHOT_COMMAND_OBSERVATION_NOT_FOUND: "当前快照没有对应命令记录",
  SNAPSHOT_TEST_PASSED: "快照中的测试已通过",
  SNAPSHOT_TEST_FAILED: "快照中的测试未通过",
  SNAPSHOT_TEST_OBSERVATION_NOT_FOUND: "当前快照没有对应测试记录",
  CODE_REVISION_CHANGED: "验证期间代码版本发生变化",
  CODE_REVISION_CONFLICT: "请求的代码版本与当前版本不一致",
  GRAPH_REVISION_CHANGED: "验证期间 CodeGraph 索引版本发生变化",
  VERIFICATION_CANCELLED: "证据验证已取消",
  VERIFICATION_DEADLINE_EXCEEDED: "证据验证超过时限",
  VERIFICATION_SOURCE_UNAVAILABLE: "缺少可用的证据来源",
  COMPONENT_READY: "组件已就绪",
  COMPONENT_DEGRADED: "组件处于降级状态",
  CAPABILITY_DISABLED: "能力已禁用",
  CAPABILITY_NOT_CONFIGURED: "能力尚未配置",
});

const details: Readonly<Record<string, string>> = Object.freeze({
  KNOWLEDGE_PREVIEW_INCOMPLETE: "后台闭环没有产出可提交的候选策略结果。系统会按重试策略重新执行；若达到最大次数仍未成功，任务将转为失败。",
  KNOWLEDGE_PREVIEW_FAILED: "知识编译流水线返回失败。请结合后台任务中的尝试记录判断具体失败阶段。",
  CANDIDATE_PREVIEW_RESULT_MISSING: "后台任务报告成功，但持久化存储中没有对应候选预览，需要检查任务完成与结果写入的原子性。",
  JOB_LEASE_EXPIRED: "任务开始执行后，工作进程未能在租约期限内持续上报心跳。常见原因是服务重启、进程退出或执行被中断；系统会在重试额度内重新执行。",
  JOB_MAX_ATTEMPTS_EXHAUSTED: "任务已经用完自动重试额度，需要先查看各次尝试的失败记录，再决定是否手动重试。",
  JOB_NON_RETRYABLE_FAILURE: "后台判断该错误继续重试也不会自行恢复，需要修复配置或输入后重新发起。",
  JOB_HANDLER_FAILED: "任务处理器抛出了未归类异常，请在后台任务页查看对应尝试记录。",
  JOB_HANDLER_NOT_FOUND: "当前运行版本没有注册该任务类型的处理器，需检查组件部署与版本匹配。",
  CODEGRAPH_NOT_INITIALIZED: "ZhiLoop 不会替你修改业务仓库。请先在目标项目中明确初始化 CodeGraph，再重新验证。",
  CODEGRAPH_INDEX_STALE: "代码索引与当前 Git/文件状态不一致，本次结果不会被当作可发布证据。更新索引后可重试。",
  CODE_REVISION_CHANGED: "验证开始和结束时检测到不同代码版本。本批结果已整体丢弃，后台可在稳定版本上重试。",
  GRAPH_REVISION_CHANGED: "验证期间 CodeGraph 索引发生变化。本批结果已整体丢弃，避免混用不同版本的代码事实。",
  SNAPSHOT_COMMAND_OBSERVATION_NOT_FOUND: "命令与测试证据只读取当前不可变会话快照；保鲜阶段不会重新执行历史命令。",
  SNAPSHOT_TEST_OBSERVATION_NOT_FOUND: "当前保鲜任务没有原始会话快照，因此保持未知，不会把缺失记录当作测试通过。",
});

export function p2EnumLabel(value: string): string {
  return labels[value] ?? value;
}

export function p2ReasonDetail(value: string): string | undefined {
  return details[value];
}
