const good = new Set(["READY", "SUCCEEDED", "COMPLETED", "ROLLED_BACK", "CAPTURED_CURRENT", "INJECTED", "FRESH", "SUPPORTED", "USER_ACCEPTED"]);
const warning = new Set(["DEGRADED", "NOT_VERIFIED", "CAPTURED_PARTIAL", "PARTIAL_SNAPSHOT", "SHADOWED", "RETRY_WAIT", "REVALIDATE", "CONFLICT", "PROPOSED", "PARTIAL", "UNSUPPORTED", "SUPPRESSED", "INELIGIBLE", "COMMITTING", "ROLLING_BACK", "ROLLBACK_CONFLICT", "CORRECTION"]);
const bad = new Set(["FAILED", "ERROR", "REFUTED", "CRITICAL", "USER_REJECTED"]);

const labels: Readonly<Record<string, string>> = Object.freeze({
  ACCEPTED: "已接受",
  ACTIVE: "已启用",
  ASK_USER: "需要人工确认",
  BLOCKED: "已阻塞",
  BOUNDED: "有界",
  CANCELLED: "已取消",
  CAPTURED_CURRENT: "已采集至最新",
  CAPTURED_PARTIAL: "部分采集",
  COMPLETE: "完整",
  COMPLETED: "已完成",
  COMPLETE_SNAPSHOT: "完整快照",
  CRITICAL: "严重",
  DEGRADED: "降级",
  DECIDED: "已完成决策",
  DISABLED: "已禁用",
  DISCOVERED_NOT_CAPTURED: "待采集",
  EFFECTIVE: "已生效",
  ELIGIBLE: "符合条件",
  ERROR: "错误",
  FAILED: "失败",
  FRESH: "数据新鲜",
  HEALTHY: "健康",
  IMPLEMENTED: "已实现",
  INELIGIBLE: "不符合条件",
  INJECTED: "已注入",
  INVALID_INPUT: "输入无效",
  IRREVERSIBLE: "不可逆",
  NO_CONTEXT: "无可用上下文",
  NOT_APPLICABLE: "不适用",
  NOT_CONFIGURED: "未配置",
  NOT_PROJECTED: "尚未建立保鲜投影",
  NOT_REQUIRED: "无需代码保鲜",
  NOT_IMPLEMENTED: "未实现",
  NOT_VERIFIED: "未验证",
  OFF: "关闭",
  OFFLINE: "离线",
  PARTIAL: "部分完成",
  PARTIAL_SNAPSHOT: "部分快照",
  PASS: "通过",
  PENDING: "等待中",
  PROPOSED: "待确认",
  PROVIDER_ERROR: "提供方错误",
  POLLING: "轮询中",
  QUEUED: "排队中",
  READY: "就绪",
  REJECTED: "已拒绝",
  RECONNECTING: "重新连接中",
  RESYNC_REQUIRED: "需要重新同步",
  RETRY_WAIT: "等待重试",
  REVALIDATE: "等待重新验证",
  REFUTED: "验证不支持",
  REVERSIBLE: "可回滚",
  CONFLICT: "与当前代码冲突",
  RETRY_WITH_CONTEXT: "补充上下文后重试",
  RETRY_WITH_CORRECTION: "修正后重试",
  ROLLED_BACK: "已回滚",
  ROLLING_BACK: "正在回滚",
  ROLLBACK_CONFLICT: "回滚存在冲突",
  COMMITTING: "正在提交",
  RUNNING: "运行中",
  SATISFIED: "已满足",
  SHADOW: "影子模式",
  SHADOWED: "影子投递",
  SKIPPED: "已跳过",
  SOURCE_UNAVAILABLE: "来源不可用",
  STALE: "已过期",
  STARTING: "启动中",
  SUCCEEDED: "成功",
  SUPPORTED: "验证支持",
  SUPERSEDED: "已替代",
  SUPPRESSED: "已抑制",
  TIMEOUT: "超时",
  UNKNOWN: "未知",
  UNSATISFIED: "未满足",
  UNSUPPORTED: "不支持",
  USER_ACCEPTED: "用户已接受",
  USER_REJECTED: "用户已拒绝",
  CORRECTION: "用户已纠正",
  VERIFIED: "已验证",
  WARNING: "警告",
});

export function statusLabel(status: string): string {
  return labels[status] ?? `未知状态（${status}）`;
}

export function StatusBadge({ status }: { readonly status: string }): React.JSX.Element {
  const tone = good.has(status) ? "good" : warning.has(status) ? "warning" : bad.has(status) ? "bad" : "neutral";
  return <span className={`status-tag ${tone}`} title={status}>{statusLabel(status)}</span>;
}
